import { StyleSheet } from 'react-native';

import { palette, radius } from '@/constants/theme';

export const followImportStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.background },
  header: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 14 },
  headerText: { flex: 1, minWidth: 0 },
  title: { color: palette.text, fontSize: 26, fontWeight: '900', letterSpacing: -1 },
  subtitle: { marginTop: 4, color: palette.textSecondary, fontSize: 12, lineHeight: 17 },
  iconButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.surface, borderRadius: radius.control },
  browserFrame: { flex: 1, overflow: 'hidden', marginHorizontal: 12, backgroundColor: palette.surface, borderRadius: radius.card },
  webView: { flex: 1, backgroundColor: palette.surface },
  loginActions: { gap: 10, padding: 14 },
  privacy: { color: palette.textMuted, textAlign: 'center', fontSize: 10, lineHeight: 15 },
  primaryButton: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 16, backgroundColor: palette.accent, borderRadius: radius.control },
  primaryButtonText: { color: palette.accentText, fontSize: 14, fontWeight: '900' },
  disabled: { opacity: 0.34 },
  tools: { flexDirection: 'row', gap: 8, paddingHorizontal: 14, paddingBottom: 10 },
  search: { flex: 5, height: 46, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, backgroundColor: palette.surface, borderRadius: radius.card },
  searchInput: { flex: 1, color: palette.text, fontSize: 13 },
  selectAll: { flex: 1, minWidth: 70, height: 46, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.surface, borderRadius: radius.card },
  selectAllText: { color: palette.textSecondary, fontSize: 11, fontWeight: '800' },
  accentText: { color: palette.accent },
  listContent: { marginHorizontal: 14, overflow: 'hidden', backgroundColor: palette.surface, borderRadius: radius.card },
  row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border },
  selectedSurface: { backgroundColor: palette.surfaceSelected },
  avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: palette.surfaceRaised },
  avatarFallback: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: palette.surfaceRaised },
  avatarText: { color: palette.text, fontSize: 14, fontWeight: '900' },
  rowText: { flex: 1, minWidth: 0 },
  name: { color: palette.text, fontSize: 15, fontWeight: '800' },
  status: { marginTop: 2, color: palette.textMuted, fontSize: 10, fontWeight: '700' },
  statusReady: { color: palette.textSecondary },
  checkbox: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.surfaceRaised, borderRadius: radius.control },
  checkboxActive: { backgroundColor: palette.surfaceSelected },
  empty: { padding: 30, color: palette.textSecondary, textAlign: 'center', fontSize: 12 },
  footer: { gap: 8, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 4, backgroundColor: palette.background },
  selectionSummary: { color: palette.textSecondary, textAlign: 'center', fontSize: 11, fontWeight: '700' },
  pressed: { opacity: 0.72 },
});
